### ISSUE TITLE
Link to hackEDU Shipit

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/shipped#40]
There should be a link to submit projects through https://shipit.hackedu.us/.

**Comment by zachlatta** [comment]
Can you add this to the README? There's currently a reference in
CONTRIBUTING.md, but it's not clear at all.

--
Zach Latta http://zachlatta.com https://github.com/zachlatta
https://twitter.com/zachlatta


On Tue, Jan 6, 2015, at 03:29 PM, Max Wofford wrote:
> There should be a link to submit projects through
> https://shipit.hackedu.us/.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/hackedu/shipped/issues/40

**Comment by ad510** [comment]
Can we add it to the home page too? It would be annoying to take 2 clicks to get to the submit page.

**Comment by MaxWofford** [comment]
Would this look better as a separate button on top that says "Ship your own project", or make the current title link to https://shipit.hackedu.us/.

**Comment by zachlatta** [comment]
See #43 for the PR that @ad510 is working on.
