### ISSUE TITLE
Cards don't line up across multiple lines

### ISSUE THREAD

**Issue by zachlatta** [hackedu/shipped#51]
![tmp](https://cloud.githubusercontent.com/assets/992248/5830572/6253c9ae-a0d7-11e4-9ee3-04bcee4de18c.png)

**Comment by MaxWofford** [comment]
I don't know of a good way to do this in css without truncating the descriptions, or the columns being unbalanced.

**Comment by zachlatta** [comment]
What do you mean by the "columns being unbalanced"?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
If I build this with columns, then put an equal number of cards in each column, the column with the longest cards will stretch further than the others.

**Comment by zachlatta** [comment]
ah, gotcha. is this a particularly bad/noticeable issue?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Fixed by b0b282a9e7b2131c4d326b9388aa8394fbaba5c8

**Comment by MaxWofford** [comment]
This doesn't work on mobile on the lower half of the page. Tested with android chrome.

**Comment by MaxWofford** [comment]
Might implement based on this: http://codepen.io/HugoGiraudel/pen/LklCv

**Comment by zachlatta** [comment]
Sounds good!

**Comment by MaxWofford** [comment]
I think this looks bad because the projects are sorted into categories by hackathon. Maybe having them all in one place, but giving them tags would be better?

**Comment by MaxWofford** [comment]
For the time being, maybe it would be better to just skip the hackathon categories.

**Comment by zachlatta** [comment]
I'm okay with this.

**Comment by MaxWofford** [comment]
Closing this because it was fixed by #70
