### ISSUE TITLE
Add section to readme on getting started

### ISSUE THREAD

**Issue by zachlatta** [hackedu/shipped#52]
Prereqs:

* Jekyll

How to run server

That sort of thing

**Comment by MaxWofford** [comment]
This should be fixed by https://github.com/hackedu/shipped/tree/issue%2352-add-section-to-readme-on-getting-started

**Comment by zachlatta** [comment]
sweet, can you send a PR?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
